{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rustcost.fullname" . }}
  labels:
    app: {{ include "rustcost.name" . }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
      - nodes/status
    verbs: ["get"]
{{- end }}
