{{- if and .Values.postgresql.enabled .Values.postgresql.runMigrations }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rustcost.fullname" . }}-migrations
  labels:
    {{- include "rustcost.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: null   # keep pods forever
  template:
    metadata:
      labels:
        app: {{ include "rustcost.name" . }}-migrations
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["rustcost"]
          args: ["migrate"]   # assumes your binary supports `migrate` command
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ include "rustcost.fullname" . }}-postgresql:5432/{{ .Values.postgresql.database }}"

{{- end }}
