{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rustcost.fullname" . }}-postgresql
  labels:
    {{- include "rustcost.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rustcost.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "rustcost.name" . }}-postgresql
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "rustcost.name" . }}-postgresql
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
              name: tcp-postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustcost.fullname" . }}-postgresql
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustcost.fullname" . }}-postgresql
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustcost.fullname" . }}-postgresql
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
