{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustcost.fullname" . }}-postgresql
  labels:
    {{- include "rustcost.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: tcp-postgres
  selector:
    app: {{ include "rustcost.name" . }}-postgresql
    release: {{ .Release.Name }}
{{- end }}
