
{{- if .Values.postgres.enable }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace | default "rustcost" }}
  labels:
    app: postgres
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      name: postgres
  clusterIP: None
  selector:
    app: postgres
{{- end }}
