{{- if .Values.postgres.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: rustcost-postgres
  namespace: {{ .Release.Namespace | default "rustcost" }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
{{- end }}
