apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rustcost.fullname" . }}
  labels:
    {{- include "rustcost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rustcost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rustcost.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rustcost.fullname" . }}

      initContainers:
        - name: wait-for-postgres
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              apk add --no-cache postgresql-client
              until psql "$DATABASE_URL" -c "SELECT 1;" >/dev/null 2>&1; do
                echo "waiting for postgres..."
                sleep 1
              done
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustcost.fullname" . }}-postgresql
                  key: DATABASE_URL
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustcost.fullname" . }}-postgresql
                  key: DATABASE_URL

            - name: NODE_EXPORTER_URLS
              value: "http://{{ include "rustcost.fullname" . }}-node-exporter:{{ .Values.nodeExporter.port }}/metrics"

            - name: CADVISOR_URLS
              value: "http://{{ include "rustcost.fullname" . }}-cadvisor:{{ .Values.cadvisor.port }}/metrics"

            # Enable debug logs for Diesel + tracing
            - name: RUST_LOG
              value: "info,diesel=debug"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
