apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rustcost.fullname" . }}
  labels:
    {{- include "rustcost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rustcost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rustcost.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rustcost.fullname" . }}
      initContainers:
        - name: wait-for-migrations
          image: alpine:3.19
          command:
            - sh
            - -c
            - >
              apk add --no-cache postgresql-client &&
              for i in $(seq 1 60); do
                psql "$DATABASE_URL" -c "SELECT 1 FROM __diesel_schema_migrations;" >/dev/null 2>&1 && exit 0;
                echo "waiting for migrations... ($i/60)";
                sleep 5;
              done;
              echo "migrations not ready after 5 minutes, exiting";
              exit 1
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustcost.fullname" . }}-postgresql
                  key: DATABASE_URL
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustcost.fullname" . }}-postgresql
                  key: DATABASE_URL

            - name: NODE_EXPORTER_URLS
              value: "http://{{ include "rustcost.fullname" . }}-node-exporter:{{ .Values.nodeExporter.port }}/metrics"

            - name: CADVISOR_URLS
              value: "http://{{ include "rustcost.fullname" . }}-cadvisor:{{ .Values.cadvisor.port }}/metrics"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
