apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rustcost.fullname" . }}
  labels:
    {{- include "rustcost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rustcost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rustcost.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.postgresql.enabled }}{{ include "rustcost.fullname" . }}-postgresql{{ else }}{{ .Values.postgresql.existingSecret | default "postgres-secret" }}{{ end }}
                  key: DATABASE_URL
            - name: NODE_EXPORTER_URLS
              value: "http://{{ include "rustcost.fullname" . }}-node-exporter:{{ .Values.nodeExporter.port }}/metrics"
            - name: CADVISOR_URLS
              value: "http://{{ include "rustcost.fullname" . }}-cadvisor:{{ .Values.cadvisor.port }}/metrics"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
