apiVersion: v1
kind: Service
metadata:
  name: rustcost
  namespace: { { .Release.Namespace | default "rustcost" } }
  labels:
    app: rustcost
spec:
  type: { { .Values.service.type } }
  selector:
    app: rustcost
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.app.port | int } }
      name: http
